apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: myapp
    image: nginx

    # 1. Direct environment variables
    env:
    - name: APP_MODE
      value: "production"
    - name: STATIC_PORT
      value: "8080"

    # 2. Import all keys from ConfigMap as env vars
    envFrom:
    - configMapRef:
        name: app-config

    # 3. Import all keys from Secret as env vars
    - secretRef:
        name: db-secret

    # 4. Inject individual keys from ConfigMap and Secret
    env:
    - name: CONFIG_SINGLE_KEY
      valueFrom:
        configMapKeyRef:
          name: app-config       # ConfigMap object name
          key: PORT              # Specific key inside ConfigMap
    - name: SECRET_SINGLE_KEY
      valueFrom:
        secretKeyRef:
          name: db-secret        # Secret object name
          key: DB_USER           # Specific key inside Secret

    # 5. Mount ConfigMap and Secret as files
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config           # inside container
    - name: secret-volume
      mountPath: /etc/secret

  volumes:
  - name: config-volume
    configMap:
      name: app-config           # Mount entire ConfigMap as files
  - name: secret-volume
    secret:
      secretName: db-secret      # Mount entire Secret as files
